# Generated by Django 3.2.10 on 2022-09-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=256, verbose_name='email verification token'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=256, verbose_name='email verification token'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hashcode',
            field=models.CharField(blank=True, max_length=256, verbose_name='password hashcode'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_otp',
            field=models.CharField(blank=True, max_length=256, verbose_name='password token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='username'),
        ),
    ]
